name: pity_cash
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_splash_screen: ^1.3.0
  animate_do: ^3.0.1
  lottie: ^2.3.0
  cached_network_image: ^3.2.0
  lazy_load_scrollview: ^1.0.0
  cupertino_icons: ^1.0.2
  intl: ^0.18.0
  file_picker: ^5.0.1
  path_provider: ^2.0.11
  flutter_bloc: ^8.0.0
  permission_handler: ^10.0.0
  flutter_typeahead: ^3.2.1
  flutter_dropzone: ^3.0.6
  dio: ^5.0.0
  shared_preferences: ^2.0.15
  connectivity_plus_platform_interface: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.3
  flutter_lints: ^2.0.0

# Konfigurasi icon
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/pitycash_icons1.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/pitycash_icons1.png"

flutter:
  uses-material-design: true
  assets:
    - assets/piticash_log.png
    - assets/bg_logo_piticash.png
    - assets/icon/pitycash_icons.png
